const FETCH_TODO_REQUEST = 'FETCH_TODO_REQUEST';
const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS';
const FETCH_TODO_ERROR = 'FETCH_TODO_ERROR';

const CREATE_TODO_REQUEST = 'CREATE_TODO_REQUEST';
const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
const CREATE_TODO_ERROR = 'CREATE_TODO_ERROR';

const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST';
const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
const UPDATE_TODO_ERROR = 'UPDATE_TODO_ERROR';

const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR';

const COMPLETE_TODO_REQUEST = 'COMPLETE_TODO_REQUEST';
const COMPLETE_TODO_SUCCESS = 'COMPLETE_TODO_SUCCESS';
const COMPLETE_TODO_ERROR = 'COMPLETE_TODO_ERROR';

const SEARCH_TODO_REQUEST = 'SEARCH_TODO_REQUEST';

export {
  FETCH_TODO_REQUEST,
  FETCH_TODO_SUCCESS,
  FETCH_TODO_ERROR,
  CREATE_TODO_REQUEST,
  CREATE_TODO_SUCCESS,
  CREATE_TODO_ERROR,
  UPDATE_TODO_REQUEST,
  UPDATE_TODO_SUCCESS,
  UPDATE_TODO_ERROR,
  DELETE_TODO_REQUEST,
  DELETE_TODO_SUCCESS,
  DELETE_TODO_ERROR,
  COMPLETE_TODO_REQUEST,
  COMPLETE_TODO_SUCCESS,
  COMPLETE_TODO_ERROR,
  SEARCH_TODO_REQUEST,
};
